### ISSUE TITLE
Get apps API of Store fails when there are unpublished apps.

### ISSUE THREAD

**Issue by rushmin** [wso2/product-app-manager#358]
**Description:**

When there is an unpublished app following API doesn't return even the published apps for the user.

http://localhost:9763/store/apis/v1/assets/webapp

In the logs following error message is printed.

[2017-10-14 18:01:17,115]  WARN - CacheBackedRegistry User user1 is not authorized to read the resource /_system/governance/appmgt/applicationdata/provider/admin/app5/v1/webapp.
[2017-10-14 18:01:17,115] ERROR - GovernanceUtils Error in retrieving governance artifact by path. path: /appmgt/applicationdata/provider/admin/app5/v1/webapp.
org.wso2.carbon.registry.core.secure.AuthorizationFailedException: User user1 is not authorized to read the resource /_system/governance/appmgt/applicationdata/provider/admin/app5/v1/webapp.
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:164)
	at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:620)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:60)
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:603)
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:600)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:600)
	at org.wso2.carbon.governance.api.util.GovernanceUtils.retrieveGovernanceArtifactByPath(GovernanceUtils.java:835)
	at org.wso2.carbon.governance.api.util.GovernanceUtils.findGovernanceArtifacts(GovernanceUtils.java:1585)
	at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.findGovernanceArtifacts(GovernanceArtifactManager.java:640)
	at org.wso2.carbon.governance.api.generic.GenericArtifactManager.findGenericArtifacts(GenericArtifactManager.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.artifacts_25._c_anonymous_9(artifacts:171)
	at org.mozilla.javascript.gen.artifacts_25.call(artifacts)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.store.modules.c3._c_anonymous_4(/store/modules/asset.js:151)
	at org.jaggeryjs.rhino.store.modules.c3.call(/store/modules/asset.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.jaggeryjs.rhino.store.modules.c3._c_anonymous_22(/store/modules/asset.js:260)
	at org.jaggeryjs.rhino.store.modules.c3.call(/store/modules/asset.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.store.apis.v_1.c0._c_anonymous_1(/store/apis/v1/assets.jag:107)
	at org.jaggeryjs.rhino.store.apis.v_1.c0.call(/store/apis/v1/assets.jag)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_71(/store/modules/store.js:1099)
	at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.mozilla.javascript.gen._store__server_js_14._c_anonymous_17([store]/server.js:286)
	at org.mozilla.javascript.gen._store__server_js_14.call([store]/server.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_70(/store/modules/store.js:1093)
	at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.store.apis.v_1.c0._c_script_0(/store/apis/v1/assets.jag:6)
	at org.jaggeryjs.rhino.store.apis.v_1.c0.call(/store/apis/v1/assets.jag)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.jaggeryjs.rhino.store.apis.v_1.c0.call(/store/apis/v1/assets.jag)
	at org.jaggeryjs.rhino.store.apis.v_1.c0.exec(/store/apis/v1/assets.jag)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)
	at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)
	at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)
	at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
rushmin

**Affected Product Version:**

1.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1) Create and publish few apps.

2) Invoke the API using the credentials of a store user.

3) A list of published apps will be returned.

4) Now unpublish one app and invoke the same API as in step 2

5) An empty list will be returned and the above error message is printed in the logs.

**Related Issues:**

**Comment by madurangasiriwardena** [comment]
Closing the issues since the repo is no longer actively maintained.
